const fs = require('fs');
const lines = [
  '/**',
  ' * SUBSTRATE BASE CLASS — z = x*y^2 lens foundation',
  ' *',
  ' * A substrate is a pure lens: read manifold coordinates, return domain data.',
  ' * Cache is write-invalidated (not time-based) — consistent with lens purity.',
  ' * A clock-expiry cache stores temporal state inside a lens — violates purity.',
  ' *',
  ' * Contract for subclasses:',
  ' *   name()              => unique string id',
  ' *   extract(coordinate) => read manifold.read(coordinate), return domain object',
  ' *   validate(data)      => return bool',
  ' *   getSchema()         => return schema descriptor (optional)',
  ' */',
  '',
  'class SubstrateBase {',
  '  constructor(manifold, config = {}) {',
  '    this.manifold = manifold;',
  '    this.config = config;',
  '    this._cache = new Map();',
  '    this._listeners = new Map();',
  '    // Write-invalidated cache: evict on manifold write, not on a clock.',
  '    if (manifold && manifold.on) {',
  '      manifold.on('\''write'\'', (entry) => {',
  '        if (entry && entry.coordinate !== undefined)',
  '          this._cache.delete(this._hash(entry.coordinate));',
  '      });',
  '    }',
  '  }',
  '',
  '  // -- Override in subclasses -------------------------------------------',
  '  name()              { return '\''substrate-base'\''; }',
  '  extract(coordinate) { return this.manifold.read(coordinate) || {}; }',
  '  validate(data)      { return true; }',
  '  getSchema()         { return {}; }',
  '',
  '  // -- Standard operations -----------------------------------------------',
  '',
  '  // Extract with write-invalidated cache (safe to call every frame)',
  '  extractCached(coordinate) {',
  '    const h = this._hash(coordinate);',
  '    if (this._cache.has(h)) return this._cache.get(h);',
  '    const data = this.extract(coordinate);',
  '    this._cache.set(h, data);',
  '    return data;',
  '  }',
  '',
  '  // Batch extract — coordinates is any iterable',
  '  extractBatch(coordinates) { return Array.from(coordinates, c => this.extract(c)); }',
  '',
  '  // Extract from manifold neighborhood',
  '  extractNearby(center, radius = 10) {',
  '    return this.manifold.queryNearby(center, radius)',
  '      .map(e => ({ coordinate: e.coordinate, data: this.extract(e.coordinate), distance: e.distance }));',
  '  }',
  '',
  '  // Register a change listener for a coordinate; returns an id for removal',
  '  watch(coordinate, callback) {',
  '    const h = this._hash(coordinate);',
  '    const id = h + '\''-'\'' + (Math.random() * 1e9 | 0);',
  '    if (!this._listeners.has(h)) this._listeners.set(h, []);',
  '    this._listeners.get(h).push({ id, callback });',
  '    return id;',
  '  }',
  '',
  '  // Remove a previously registered listener',
  '  unwatch(listenerId) {',
  '    for (const [h, list] of this._listeners) {',
  '      const next = list.filter(l => l.id !== listenerId);',
  '      if (next.length < list.length) { this._listeners.set(h, next); return; }',
  '    }',
  '  }',
  '',
  '  // Fire all listeners for a coordinate (call from subclasses on mutation)',
  '  notifyListeners(coordinate, newData) {',
  '    const list = this._listeners.get(this._hash(coordinate));',
  '    if (list) for (const { callback } of list) { try { callback(newData); } catch (e) {} }',
  '  }',
  '',
  '  // Evict one or all cache entries',
  '  clearCache(coordinate) {',
  '    coordinate ? this._cache.delete(this._hash(coordinate)) : this._cache.clear();',
  '  }',
  '',
  '  // Diagnostic snapshot',
  '  getCacheStats() {',
  '    return {',
  '      substrateName: this.name(),',
  '      cachedItems: this._cache.size,',
  '      listeners: [...this._listeners.values()].reduce((n, a) => n + a.length, 0),',
  '    };',
  '  }',
  '',
  '  // -- Internal ----------------------------------------------------------',
  '',
  '  // Fast coordinate hash — no JSON.stringify; join is O(n) and allocation-free',
  '  _hash(coord) {',
  '    if (Array.isArray(coord)) return coord.join('\'':'\'');',
  '    if (coord !== null && typeof coord === '\''object'\'') return Object.values(coord).join('\'':'\'');',
  '    return String(coord);',
  '  }',
  '',
  '  // Backward-compat alias',
  '  _coordinateHash(coord) { return this._hash(coord); }',
  '}',
  '',
  'if (typeof module !== '\''undefined'\'' && module.exports) module.exports = SubstrateBase;',
  'if (typeof window !== '\''undefined'\'') window.SubstrateBase = SubstrateBase;'
];
fs.writeFileSync('c:/projects/manifold/js/manifold-core/substrate_base.js', lines.join('\n') + '\n', 'utf8');
console.log('OK', fs.statSync('c:/projects/manifold/js/manifold-core/substrate_base.js').size, 'bytes');
